"""
core/report_engine.py — Generate human-readable snapshot text.

Produces:
  - Plain-text summary for UI display
  - HTML-formatted version for email body
  - CSV path via CSVManager
"""

from __future__ import annotations
from datetime import datetime
from typing import List, Tuple

from app.models import User, Item


class ReportEngine:
    """Pure logic — no I/O, no UI. Converts data → formatted strings."""

    # ── Plain text (monospace-friendly) ───────────────────────────────────────
    @staticmethod
    def user_snapshot_text(user: User, items: List[Item], month: str) -> str:
        lines = [
            "=" * 48,
            f"  SPAYLATER SNAPSHOT",
            f"  {month}",
            "=" * 48,
            f"  User  : {user.name}",
            f"  Email : {user.email or '—'}",
            "-" * 48,
        ]
        if not items:
            lines.append("  No items for this month.")
        else:
            for item in items:
                lines.append(f"  {item.item:<28} ₱{item.price:>8.2f}")
        lines += [
            "-" * 48,
            f"  {'TOTAL':<28} ₱{sum(i.price for i in items):>8.2f}",
            "=" * 48,
            f"  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            "=" * 48,
        ]
        return "\n".join(lines)

    # ── Monthly summary (all users) ───────────────────────────────────────────
    @staticmethod
    def monthly_summary_text(
        month: str,
        users: List[User],
        items: List[Item],
    ) -> str:
        user_map = {u.id: u for u in users}
        # group items by user
        by_user: dict[str, List[Item]] = {}
        for item in items:
            by_user.setdefault(item.user_id, []).append(item)

        lines = [
            "=" * 52,
            f"  SPAYLATER MONTHLY REPORT — {month}",
            "=" * 52,
        ]
        grand = 0.0
        for user_id, user_items in by_user.items():
            user = user_map.get(user_id)
            name = user.name if user else user_id
            subtotal = sum(i.price for i in user_items)
            grand += subtotal
            lines.append(f"\n  ▸ {name}  (₱{subtotal:.2f})")
            for item in user_items:
                lines.append(f"      {item.item:<26} ₱{item.price:>8.2f}")
        lines += [
            "\n" + "-" * 52,
            f"  {'GRAND TOTAL':<30} ₱{grand:>10.2f}",
            "=" * 52,
        ]
        return "\n".join(lines)

    # ── HTML email body ───────────────────────────────────────────────────────
    @staticmethod
    def user_snapshot_html(user: User, items: List[Item], month: str) -> str:
        total = sum(i.price for i in items)
        rows = "".join(
            f"<tr><td style='padding:6px 12px'>{i.item}</td>"
            f"<td style='padding:6px 12px;text-align:right'>₱{i.price:.2f}</td></tr>"
            for i in items
        )
        return f"""
<html><body style="font-family:Georgia,serif;background:#0D1117;color:#E6EDF3;padding:24px">
  <h2 style="color:#E8A020">Spaylater Snapshot — {month}</h2>
  <p>Hi <strong>{user.name}</strong>, here is your Spaylater summary for <strong>{month}</strong>.</p>
  <table style="border-collapse:collapse;width:100%;max-width:480px">
    <thead>
      <tr style="background:#E8A020;color:#0D1117">
        <th style="padding:8px 12px;text-align:left">Item</th>
        <th style="padding:8px 12px;text-align:right">Price</th>
      </tr>
    </thead>
    <tbody style="background:#1C2333">{rows}</tbody>
    <tfoot>
      <tr style="background:#30363D;font-weight:bold">
        <td style="padding:8px 12px">TOTAL</td>
        <td style="padding:8px 12px;text-align:right">₱{total:.2f}</td>
      </tr>
    </tfoot>
  </table>
  <p style="color:#8B949E;font-size:12px;margin-top:24px">
    Generated by Spaylater Manager · {datetime.now().strftime('%Y-%m-%d %H:%M')}
  </p>
</body></html>
"""